# Generated by Django 3.0.3 on 2020-02-10 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
