# Generated by Django 3.0.3 on 2020-02-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0002_auto_20200210_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.TextField(blank=True, null=True, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='product',
            name='public_date',
            field=models.DateTimeField(verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
