# Generated by Django 3.0.3 on 2020-02-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0003_auto_20200211_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(unique=True, verbose_name='Ссылка на объявление'),
        ),
    ]
