# Generated by Django 3.0.3 on 2020-02-11 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0004_auto_20200211_1246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(verbose_name='Ссылка на раздел')),
                ('status', models.IntegerField(choices=[(1, 'Новое'), (2, 'Готово')], default=1, verbose_name='Статус задания')),
            ],
        ),
    ]
