# Generated by Django 3.0.3 on 2020-02-11 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0005_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
    ]
