# Generated by Django 3.0.3 on 2020-02-11 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0006_auto_20200212_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='avparser.Task', verbose_name='Задание'),
        ),
    ]
