# Generated by Django 3.0.3 on 2020-02-11 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avparser', '0007_product_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='title',
            field=models.TextField(default='Задание', verbose_name='Название задания'),
        ),
    ]
