
run_admin: avito/manage.py
	python avito/manage.py runserver

parse: avito/manage.py
	python avito/manage.py parse_avito

makemigrations: avito/manage.py
	python avito/manage.py makemigrations

migrate: avito/manage.py
	python avito/manage.py migrate
